<?php

return [
    'paragraph' => [
        'label' => '段落',
        'icon' => 'title',
        'description' => '段落',
        'aliases' => ['p', 'paragraph', 'text'],
        'isTextMenu' => true,
    ],
    'heading1' => [
        'label' => '見出し1',
        'icon' => 'format_h1',
        'description' => '見出し',
        'aliases' => ['h1', 'heading1'],
        'isTextMenu' => true,
    ],
    'heading2' => [
        'label' => '見出し2',
        'icon' => 'format_h2',
        'description' => '見出し2',
        'aliases' => ['h2', 'heading2'],
        'isTextMenu' => true,
    ],
    'heading3' => [
        'label' => '見出し3',
        'icon' => 'format_h3',
        'description' => '見出し3',
        'aliases' => ['h3', 'heading3'],
        'isTextMenu' => true,
    ],
    'heading4' => [
        'label' => '見出し4',
        'icon' => 'format_h4',
        'description' => '見出し4',
        'aliases' => ['h4', 'heading4'],
        'isTextMenu' => true,
    ],
    'heading5' => [
        'label' => '見出し5',
        'icon' => 'format_h5',
        'description' => '見出し5',
        'aliases' => ['h5', 'heading5'],
        'isTextMenu' => true,
    ],
    'heading6' => [
        'label' => '見出し6',
        'icon' => 'format_h6',
        'description' => '見出し6',
        'aliases' => ['h6', 'heading6'],
        'isTextMenu' => true,
    ],
    'bulletList' => [
        'label' => 'リスト',
        'icon' => 'format_list_bulleted',
        'description' => '順序なしリスト',
        'aliases' => ['ul', 'list'],
        'isTextMenu' => true,
    ],
    'numberedList' => [
        'label' => '番号付きリスト',
        'icon' => 'format_list_numbered',
        'description' => '番号付きリスト',
        'aliases' => ['ol', 'ordered list'],
        'isTextMenu' => true,
    ],
    'blockquote' => [
        'label' => '引用',
        'icon' => 'format_quote',
        'description' => '引用',
        'aliases' => ['quote'],
        'isTextMenu' => false,
    ],
    'codeBlock' => [
        'label' => 'コード',
        'icon' => 'code_blocks',
        'description' => 'コードブロック',
        'aliases' => ['code'],
        'isTextMenu' => false,
    ],
    'image' => [
        'label' => '画像',
        'icon' => 'photo',
        'description' => 'メディア画像',
        'aliases' => ['img', 'image', 'media'],
        'isTextMenu' => false,
    ],
    'file' => [
        'label' => 'ファイル',
        'icon' => 'draft',
        'description' => 'メディアファイル',
        'aliases' => ['file', 'media'],
        'isTextMenu' => false,
    ],
    'linkButton' => [
        'label' => 'リンクボタン',
        'icon' => 'link',
        'description' => 'リンクボタン',
        'aliases' => ['link', 'button'],
        'isTextMenu' => false,
    ],
    'table' => [
        'label' => 'テーブル',
        'icon' => 'table',
        'description' => 'テーブル',
        'aliases' => ['table'],
        'isTextMenu' => false,
    ],
    'horizontalRule' => [
        'label' => '水平罫線',
        'icon' => 'horizontal_rule',
        'description' => '水平罫線',
        'aliases' => ['hr', 'rule', 'separator'],
        'isTextMenu' => false,
    ],
    'columns2' => [
        'label' => '2カラムに分割',
        'icon' => 'view_week',
        'description' => '2カラムに分割',
        'aliases' => ['cols2', 'columns2'],
        'isTextMenu' => false,
    ],
    'columns3' => [
        'label' => '3カラムに分割',
        'icon' => 'view_week',
        'description' => '3カラムに分割',
        'aliases' => ['cols3', 'columns3'],
        'isTextMenu' => false,
    ],
];
