services:
  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  www:
    image: atsu666/acms:8.3
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../ablogcms:/var/www/html
      - ../plugins:/var/www/plugins
      - /etc/localtime:/etc/localtime:ro

volumes:
  mariadb-data:
